### ISSUE TITLE
DO NOT USE v0.4.1 - SCALING ISSUES

### ISSUE THREAD

**Issue by applike-ss** [spotinst/terraform-spotinst-ocean-aws-k8s-vng#10]
So today i have had a nice conversation with Ben from the support team of spotinst.

We've stumbled upon an issue that likely only few if anyone have had before, otherwise the fix would've been found faster.

When using v0.4.1 (which we did), you can get into scaling trouble with messages like `Can't Spin Instances: Code: ValidationError, Message: can't spin spot due to duplicate tags error`.

v0.4.1 was never published as of today and we were only using it because it enabled us to name our ec2 nodes like we wanted to by specifying the name tag.

This is just a reminder and a "helping hand" issue and not necessarily the fix needs to be done here.

The root cause is the label `spotinst:ocean:launchspec:name`, which was introduced in v0.4.1.

Simply deleting the tag manually from the vng seems to fix the problems, but obviously that does not work when working with IaC.

**Comment by stevenfeltner** [comment]
@applike-ss Thanks for sharing. We will review and address it accordingly.
